import {describe, expect, it} from '@jest/globals';
import {deserializeHumaneMsg, serializeHumaneMsg} from './serialization';

describe('MsgPack serialization', () => {
  it('should be able to decode hardcoded array generated by java serializer', () => {
    // PayloadMsg[msgId=msgId, chatId=chatId, userId=userId, timestamp=2022-09-24T19:18:03.481955Z, status=READ, payload=payload]
    const serializedPlaintext = Uint8Array.from([
      -105, 3, -91, 109, 115, 103, 73, 100, -90, 99, 104, 97, 116, 73, 100, -90,
      117, 115, 101, 114, 73, 100, -41, -1, 114, -24, 50, -32, 99, 47, 87, -21,
      3, -89, 112, 97, 121, 108, 111, 97, 100,
    ]);
    console.log(serializedPlaintext, serializedPlaintext.length);

    const decoded = deserializeHumaneMsg(serializedPlaintext);
    console.log(decoded);

    const encoded = serializeHumaneMsg(decoded);
    console.log('encoded', encoded);

    expect(encoded).toStrictEqual(serializedPlaintext);
  });
});
